"""
Remediation pull requests: findings that fix themselves, for review.

The product principle up to now was advisory-only. That principle is revised,
with a boundary worth stating precisely: **the application acts, the agent
still cannot.** Remediation happens by opening pull requests through the
GitHub App -- repository write, subject to the customer's own review and
merge controls -- while the in-cluster agent keeps its get/list/watch-only
ClusterRole. Acting through the customer's GitOps pipeline is action with an
audit trail, a reviewer, and a revert button; a cluster-write agent is action
with none of those, and nothing in this module requires one.

## Only deterministic remediations

A remediation PR is generated, not authored, so it must be correct by
construction:

* **PodDisruptionBudget creation** -- the flagship. A missing PDB on a
  load-bearing workload is the most common resilience finding, and the fix is
  a *new file*: nothing existing is edited, no manifest has to be located in
  the repository, and the generated object cannot break running workloads
  because a PDB only constrains voluntary eviction.

Deliberately absent, with reasons rather than TODOs:

* **Image digest pinning** needs the resolved digest, which the agent does
  not collect (it reads specs, and the digest lives in pod status). Wrong
  digest = broken deploy; no digest = no PR.
* **Readiness probes** encode application semantics -- the right port, path,
  and timing -- that no analysis can derive. A generated probe that guesses
  wrong takes a healthy workload out of rotation, which is worse than the
  missing probe.

## The PDB itself

``maxUnavailable: 1``, never ``minAvailable``. A generated ``minAvailable``
equal to the replica count is the exact anti-pattern the resilience analysis
flags on other people's clusters -- it protects nothing and blocks every node
drain. ``maxUnavailable: 1`` cannot express that failure mode: whatever the
replica count does later, evictions proceed one pod at a time and at least
``replicas - 1`` stay up. Single-replica workloads are skipped entirely; a
PDB on one replica either blocks all maintenance or permits everything, and
the real fix -- a second replica -- is a capacity decision this module does
not get to make.
"""

from __future__ import annotations

import logging
from typing import Any

from .blast_radius import build_dependency_graph, compute_blast_radius
from .git_provider import GitHubApp, branch_name
from . import resilience

log = logging.getLogger(__name__)

# Where generated manifests land in the customer's repository. A dedicated
# directory makes the provenance obvious in the tree and gives GitOps tooling
# one path to include.
REMEDIATION_DIR = "cloudoptimizer/remediations"


def pdb_manifest(workload: dict) -> str:
    """The PodDisruptionBudget for a workload, as committable YAML."""
    name = workload.get("name")
    namespace = workload.get("namespace") or "default"
    selector = workload.get("pod_labels") or {}
    if not name or not selector:
        raise ValueError(
            f"{workload.get('key')} has no name or pod labels; a PDB without "
            "a selector matches nothing."
        )

    selector_lines = "\n".join(
        f"      {key}: {value}" for key, value in sorted(selector.items())
    )
    return f"""# Generated by CloudOptimizer.
#
# {workload.get('key')} is load-bearing and had no PodDisruptionBudget:
# nothing prevented a node drain from evicting every replica at once, so
# routine maintenance was an outage for everything downstream.
#
# maxUnavailable: 1 rather than minAvailable deliberately. A minAvailable
# equal to the replica count permits zero disruptions -- it blocks every node
# drain while protecting nothing. maxUnavailable: 1 lets maintenance proceed
# one pod at a time whatever the replica count becomes later.
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {name}-pdb
  namespace: {namespace}
  labels:
    app.kubernetes.io/managed-by: cloudoptimizer
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
{selector_lines}
"""


def plan(
    snapshot: dict,
    cei_by_workload: dict[str, dict] | None = None,
) -> list[dict[str, Any]]:
    """
    Remediations this cluster warrants, from the resilience findings.

    Reuses the analysis rather than re-deriving its own criteria: if the
    finding logic changes, what gets remediated changes with it, and the two
    can never disagree about what needs fixing.
    """
    cei_by_workload = cei_by_workload or {}
    workloads = {w["key"]: w for w in (snapshot.get("workloads") or []) if w.get("key")}
    findings = resilience.analyze(snapshot, cei_by_workload)["findings"]
    graph = build_dependency_graph(snapshot)

    proposals = []
    for finding in findings:
        if finding["kind"] != "missing_disruption_budget":
            continue
        workload = workloads.get(finding["workload_key"])
        if workload is None:
            continue
        if (workload.get("replicas_desired") or 0) < 2:
            # A PDB on one replica blocks all maintenance or permits
            # everything; the real fix is a second replica, which is a
            # capacity decision, not a generated file.
            continue
        try:
            manifest = pdb_manifest(workload)
        except ValueError as exc:
            log.info("Skipping PDB for %s: %s", finding["workload_key"], exc)
            continue

        radius = compute_blast_radius(
            snapshot, finding["workload_key"], cei_by_workload, graph=graph
        )
        safe_name = f"{workload.get('namespace')}-{workload.get('name')}"
        proposals.append({
            "kind": "create_pdb",
            "workload_key": finding["workload_key"],
            "path": f"{REMEDIATION_DIR}/pdb-{safe_name}.yaml",
            "manifest": manifest,
            "finding": finding,
            "blast_radius": {
                "dependents": radius.total_affected,
                "user_facing": bool(radius.entry_points),
                "headline": radius.headline,
            },
        })
    return proposals


def _pr_body(proposal: dict) -> str:
    finding = proposal["finding"]
    radius = proposal["blast_radius"]
    return f"""## What this adds

A PodDisruptionBudget for `{proposal['workload_key']}`, which is load-bearing
and currently has none.

## Why it matters

{finding['detail']}

**Blast radius:** {radius['headline']}

## Why the budget is shaped this way

`maxUnavailable: 1`, not `minAvailable`. A `minAvailable` equal to the
replica count permits zero disruptions: it blocks every node drain while
protecting nothing, and stalled cluster upgrades months later are rarely
traced back to it. `maxUnavailable: 1` lets maintenance proceed one pod at a
time regardless of how the replica count changes later.

## Safety

This is a new object; nothing existing is modified. A PodDisruptionBudget
constrains **voluntary** eviction only -- it cannot affect scheduling,
scaling, or involuntary failures, so merging it cannot break a running
workload.

---
Generated by CloudOptimizer from the live dependency graph. The in-cluster
agent remains read-only; this change acts through your repository and your
review, not through the cluster API.

🤖 Generated with CloudOptimizer
"""


def open_pr(
    app: GitHubApp,
    repo: str,
    proposal: dict,
    *,
    base: str | None = None,
) -> dict[str, Any]:
    """
    Open one remediation as a pull request.

    One proposal per PR rather than a batch: each is independently mergeable,
    independently revertible, and a reviewer can accept the PDB for the
    payment service while questioning the one for the batch queue. A batch PR
    couples unrelated decisions to the slowest reviewer.
    """
    base = base or app.default_branch(repo)
    workload_slug = proposal["workload_key"].replace("/", "-").lower()
    branch = branch_name("remediate", workload_slug)

    existing = app.find_open_pull_request(repo, branch)
    if existing:
        return {"status": "already_open", "pull_request": existing}

    app.ensure_branch(repo, branch, base)
    app.put_file(
        repo,
        proposal["path"],
        proposal["manifest"],
        branch=branch,
        message=(
            f"remediation: PodDisruptionBudget for {proposal['workload_key']}"
        ),
    )
    pull = app.open_pull_request(
        repo,
        branch=branch,
        base=base,
        title=f"Add PodDisruptionBudget for {proposal['workload_key']}",
        body=_pr_body(proposal),
    )
    return {
        "status": "opened" if pull.created else "already_open",
        "pull_request": {
            "number": pull.number,
            "url": pull.url,
            "branch": pull.branch,
            "created": pull.created,
        },
    }
