"""snapshot idempotency on captured_at not seq

Revision ID: b3e53ee63701
Revises: ce3fed463498
Create Date: 2026-08-16 11:02:55.012706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3e53ee63701'
down_revision: Union[str, Sequence[str], None] = 'ce3fed463498'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_snapshots_cluster_seq'), 'snapshots', type_='unique')
    op.create_unique_constraint('uq_snapshots_cluster_captured', 'snapshots', ['cluster_id', 'captured_at'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_snapshots_cluster_captured', 'snapshots', type_='unique')
    op.create_unique_constraint(op.f('uq_snapshots_cluster_seq'), 'snapshots', ['cluster_id', 'seq'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
