"""snapshot idempotency on captured_at not seq

Revision ID: b3e53ee63701
Revises: ce3fed463498
Create Date: 2026-08-16 11:02:55.012706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3e53ee63701'
down_revision: Union[str, Sequence[str], None] = 'ce3fed463498'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_snapshots_cluster_seq'), 'snapshots', type_='unique')
    op.create_unique_constraint('uq_snapshots_cluster_captured', 'snapshots', ['cluster_id', 'captured_at'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Restores the (cluster_id, seq) unique constraint.

    This can only succeed on a database with no duplicate seq values. After
    this migration has been live, duplicates are expected and correct: seq
    resets to 1 whenever an agent pod restarts, which is precisely why the
    constraint was moved to captured_at.

    So the downgrade works on an empty or freshly-migrated database and fails
    on a populated one. That is not a defect -- it is what it means to roll
    back to a stricter constraint. The check below turns an opaque
    IntegrityError into an explanation.
    """
    bind = op.get_bind()
    duplicates = bind.execute(
        sa.text(
            "SELECT count(*) FROM ("
            "  SELECT cluster_id, seq FROM snapshots"
            "  GROUP BY cluster_id, seq HAVING count(*) > 1"
            ") d"
        )
    ).scalar()
    if duplicates:
        raise RuntimeError(
            f"Cannot downgrade: {duplicates} (cluster_id, seq) pair(s) appear "
            "more than once. seq resets when an agent restarts, so duplicates "
            "are expected under the current schema and the older constraint "
            "cannot be restored without deleting snapshots. Delete the "
            "conflicting rows deliberately if you really intend to roll back."
        )

    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_snapshots_cluster_captured', 'snapshots', type_='unique')
    op.create_unique_constraint(op.f('uq_snapshots_cluster_seq'), 'snapshots', ['cluster_id', 'seq'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
