"""phase1 initial schema

Revision ID: ce3fed463498
Revises: 
Create Date: 2026-08-16 10:16:30.839539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ce3fed463498'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('actor_type', sa.Enum('user', 'agent', 'system', name='actor_type'), nullable=False),
    sa.Column('actor_id', sa.String(length=120), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('target_type', sa.String(length=60), nullable=True),
    sa.Column('target_id', sa.String(length=120), nullable=True),
    sa.Column('source_ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_log_action', 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_created_at'), 'audit_log', ['created_at'], unique=False)
    op.create_index('ix_audit_log_tenant_created', 'audit_log', ['tenant_id', 'created_at'], unique=False)
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('clusters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('cluster_uid', sa.String(length=64), nullable=True),
    sa.Column('provider', sa.Enum('eks', 'aks', 'gke', 'kind', 'k3s', 'openshift', 'other', 'unknown', name='cluster_provider'), server_default='unknown', nullable=False),
    sa.Column('k8s_version', sa.String(length=40), nullable=True),
    sa.Column('agent_version', sa.String(length=40), nullable=True),
    sa.Column('metrics_available', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'cluster_uid', name='uq_clusters_tenant_uid')
    )
    op.create_index(op.f('ix_clusters_last_seen_at'), 'clusters', ['last_seen_at'], unique=False)
    op.create_index(op.f('ix_clusters_tenant_id'), 'clusters', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_users_email')
    )
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('cluster_id', sa.UUID(), nullable=False),
    sa.Column('prefix', sa.String(length=40), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('length(prefix) >= 8', name='ck_api_keys_prefix_len'),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prefix', name='uq_api_keys_prefix')
    )
    op.create_index(op.f('ix_api_keys_cluster_id'), 'api_keys', ['cluster_id'], unique=False)
    op.create_index(op.f('ix_api_keys_tenant_id'), 'api_keys', ['tenant_id'], unique=False)
    op.create_table('snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('cluster_id', sa.UUID(), nullable=False),
    sa.Column('seq', sa.BigInteger(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('agent_version', sa.String(length=40), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('payload_bytes', sa.Integer(), nullable=False),
    sa.Column('node_count', sa.Integer(), nullable=False),
    sa.Column('pod_count', sa.Integer(), nullable=False),
    sa.Column('workload_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cluster_id', 'seq', name='uq_snapshots_cluster_seq')
    )
    op.create_index('ix_snapshots_cluster_received', 'snapshots', ['cluster_id', 'received_at'], unique=False)
    op.create_index(op.f('ix_snapshots_tenant_id'), 'snapshots', ['tenant_id'], unique=False)
    op.create_table('workload_samples',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('cluster_id', sa.UUID(), nullable=False),
    sa.Column('workload_key', sa.String(length=512), nullable=False),
    sa.Column('namespace', sa.String(length=253), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cpu_cores_used', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('cpu_cores_requested', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('mem_bytes_used', sa.BigInteger(), nullable=True),
    sa.Column('mem_bytes_requested', sa.BigInteger(), nullable=True),
    sa.Column('replicas_ready', sa.Integer(), nullable=True),
    sa.Column('replicas_desired', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cluster_id', 'workload_key', 'observed_at', name='uq_workload_samples_point')
    )
    op.create_index('ix_workload_samples_lookup', 'workload_samples', ['cluster_id', 'workload_key', 'observed_at'], unique=False)
    op.create_index(op.f('ix_workload_samples_tenant_id'), 'workload_samples', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workload_samples_tenant_id'), table_name='workload_samples')
    op.drop_index('ix_workload_samples_lookup', table_name='workload_samples')
    op.drop_table('workload_samples')
    op.drop_index(op.f('ix_snapshots_tenant_id'), table_name='snapshots')
    op.drop_index('ix_snapshots_cluster_received', table_name='snapshots')
    op.drop_table('snapshots')
    op.drop_index(op.f('ix_api_keys_tenant_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_cluster_id'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_clusters_tenant_id'), table_name='clusters')
    op.drop_index(op.f('ix_clusters_last_seen_at'), table_name='clusters')
    op.drop_table('clusters')
    op.drop_table('tenants')
    op.drop_index('ix_audit_log_tenant_created', table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_created_at'), table_name='audit_log')
    op.drop_index('ix_audit_log_action', table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###

    # Autogenerate creates ENUM types implicitly via the columns that use
    # them, but does NOT emit a matching DROP TYPE. Without these, a
    # downgrade leaves the types orphaned and the next upgrade fails with
    # "type ... already exists". Explicit cleanup keeps the migration
    # reversible, which is what makes it safe to test on a real database.
    sa.Enum(name='actor_type').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='cluster_provider').drop(op.get_bind(), checkfirst=True)
