"""
Remediation PRs.

The properties that must hold: only deterministic fixes are proposed, the
generated PDB can never be the anti-pattern the analysis flags elsewhere, and
the PR flow is idempotent.
"""

import yaml
import pytest

from src.services import remediation


def _workload(name, *, ns="prod", replicas=2, labels=None):
    return {
        "key": f"{ns}/Deployment/{name}", "name": name, "namespace": ns,
        "kind": "Deployment", "replicas_desired": replicas,
        "pod_labels": labels if labels is not None else {"app": name},
        "labels": {"app": name}, "images": ["repo/app@sha256:abc"],
        "probes": {"containers": 1, "with_readiness": 1, "with_liveness": 1,
                   "with_startup": 0},
        "spread": {"topology_spread_constraints": 1,
                   "topology_keys": ["kubernetes.io/hostname"],
                   "anti_affinity_required": 0, "anti_affinity_preferred": 0,
                   "priority_class": None},
        "config_refs": {"config_maps": [], "secrets": []},
    }


def _snapshot(workloads, edges):
    return {"workloads": workloads, "edges": edges, "pods": [],
            "disruption_budgets": [], "autoscalers": [], "services": []}


def _load_bearing_snapshot(replicas=2):
    """`core` has three dependents and no PDB: the flagship finding."""
    return _snapshot(
        [_workload("core", replicas=replicas)]
        + [_workload(f"svc{i}") for i in range(3)],
        [{"source": f"prod/Deployment/svc{i}", "target": "prod/Deployment/core",
          "confidence": 0.9, "source_kind": "env_reference"} for i in range(3)],
    )


# --- the manifest -----------------------------------------------------------


def test_pdb_manifest_is_valid_yaml_with_the_right_selector():
    manifest = yaml.safe_load(remediation.pdb_manifest(_workload("core")))

    assert manifest["kind"] == "PodDisruptionBudget"
    assert manifest["metadata"]["namespace"] == "prod"
    assert manifest["spec"]["selector"]["matchLabels"] == {"app": "core"}


def test_pdb_uses_max_unavailable_never_min_available():
    """
    A generated minAvailable equal to the replica count is the exact
    anti-pattern resilience.py flags: protects nothing, blocks every drain.
    The generator must be structurally unable to produce it.
    """
    manifest = yaml.safe_load(remediation.pdb_manifest(_workload("core")))

    assert manifest["spec"]["maxUnavailable"] == 1
    assert "minAvailable" not in manifest["spec"]


def test_pdb_carries_provenance():
    text = remediation.pdb_manifest(_workload("core"))

    assert "app.kubernetes.io/managed-by: cloudoptimizer" in text
    assert text.startswith("# Generated by CloudOptimizer.")


def test_workload_without_labels_is_refused():
    with pytest.raises(ValueError, match="matches nothing"):
        remediation.pdb_manifest(_workload("core", labels={}))


# --- planning ---------------------------------------------------------------


def test_plan_proposes_pdb_for_the_load_bearing_finding():
    proposals = remediation.plan(_load_bearing_snapshot())

    assert len(proposals) == 1
    proposal = proposals[0]
    assert proposal["kind"] == "create_pdb"
    assert proposal["workload_key"] == "prod/Deployment/core"
    assert proposal["path"] == "cloudoptimizer/remediations/pdb-prod-core.yaml"
    assert proposal["blast_radius"]["dependents"] == 3


def test_single_replica_workloads_are_skipped():
    """
    A PDB on one replica blocks all maintenance or permits everything; the
    real fix is a capacity decision this module does not get to make.
    """
    assert remediation.plan(_load_bearing_snapshot(replicas=1)) == []


def test_workload_with_a_pdb_already_gets_no_proposal():
    snapshot = _load_bearing_snapshot()
    snapshot["disruption_budgets"] = [{
        "name": "core-pdb", "namespace": "prod", "selector": {"app": "core"},
        "min_available": "1", "max_unavailable": None,
        "disruptions_allowed": 1, "current_healthy": 2,
        "desired_healthy": 1, "expected_pods": 2,
    }]
    assert remediation.plan(snapshot) == []


def test_isolated_workload_gets_no_proposal():
    """No dependents means the finding never fires, so neither does the fix."""
    snapshot = _snapshot([_workload("loner")], [])

    assert remediation.plan(snapshot) == []


def test_pr_body_explains_the_shape_and_the_boundary():
    proposal = remediation.plan(_load_bearing_snapshot())[0]
    body = remediation._pr_body(proposal)

    assert "maxUnavailable: 1" in body
    assert "voluntary" in body
    assert "agent remains read-only" in body


# --- the PR flow ------------------------------------------------------------


class _FakeApp:
    def __init__(self, existing=None):
        self.existing = existing
        self.calls = []

    def default_branch(self, repo):
        return "main"

    def find_open_pull_request(self, repo, branch):
        self.calls.append(("find", branch))
        return self.existing

    def ensure_branch(self, repo, branch, base):
        self.calls.append(("branch", branch, base))
        return "sha"

    def put_file(self, repo, path, content, *, message, branch, sha=None):
        self.calls.append(("put", path, branch))
        return {"path": path}

    def open_pull_request(self, repo, *, branch, base, title, body, labels=None):
        from src.services.git_provider import PullRequest
        self.calls.append(("open", branch, title))
        return PullRequest(number=7, url="https://x/pull/7", branch=branch, created=True)


def test_open_pr_creates_branch_file_and_pull_request():
    proposal = remediation.plan(_load_bearing_snapshot())[0]
    app = _FakeApp()
    result = remediation.open_pr(app, "acme/platform", proposal)

    assert result["status"] == "opened"
    assert result["pull_request"]["number"] == 7
    kinds = [c[0] for c in app.calls]
    assert kinds == ["find", "branch", "put", "open"]
    put = next(c for c in app.calls if c[0] == "put")
    assert put[1] == proposal["path"]


def test_open_pr_is_idempotent():
    """A re-run must not open a second PR for the same finding."""
    proposal = remediation.plan(_load_bearing_snapshot())[0]
    app = _FakeApp(existing={"number": 7, "html_url": "https://x/pull/7"})
    result = remediation.open_pr(app, "acme/platform", proposal)

    assert result["status"] == "already_open"
    assert [c[0] for c in app.calls] == ["find"]
